# Generated by Django 5.1.4 on 2024-12-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='uploads/')),
                ('receiver', models.CharField(max_length=50)),
                ('document', models.TextField()),
            ],
        ),
    ]
